pragma Singleton
pragma ComponentBehavior: Bound

import QtQuick
import Quickshell
import Quickshell.Io

// color palettes
// TODO: dynamic load from autogenerated
Singleton {
    property var current: autoloaded

    FileView {
        watchChanges: true
        path: "/home/desant/.config/fishy/colors.json"

        onFileChanged: reload()
        onAdapterUpdated: writeAdapter()

        // onLoadFailed: writeAdapter()

        JsonAdapter {
            id: autoloaded
            // property string test: "asdasd"

            property string background: '#101417'
            property string error: '#ffb4ab'
            property string error_container: '#93000a'
            property string inverse_on_surface: '#2d3135'
            property string inverse_primary: '#216487'
            property string inverse_surface: '#dfe3e7'
            property string on_background: '#dfe3e7'
            property string on_error: '#690005'
            property string on_error_container: '#ffdad6'
            property string on_primary: '#00344c'
            property string on_primary_container: '#c7e7ff'
            property string on_primary_fixed: '#001e2e'
            property string on_primary_fixed_variant: '#004c6c'
            property string on_secondary: '#21323e'
            property string on_secondary_container: '#d2e5f5'
            property string on_secondary_fixed: '#0b1d29'
            property string on_secondary_fixed_variant: '#374955'
            property string on_surface: '#dfe3e7'
            property string on_surface_variant: '#c1c7ce'
            property string on_tertiary: '#342b4b'
            property string on_tertiary_container: '#e8ddff'
            property string on_tertiary_fixed: '#1e1635'
            property string on_tertiary_fixed_variant: '#4a4263'
            property string outline: '#8b9198'
            property string outline_variant: '#41484d'
            property string primary: '#92cef5'
            property string primary_container: '#004c6c'
            property string primary_fixed: '#c7e7ff'
            property string primary_fixed_dim: '#92cef5'
            property string scrim: '#000000'
            property string secondary: '#b6c9d8'
            property string secondary_container: '#374955'
            property string secondary_fixed: '#d2e5f5'
            property string secondary_fixed_dim: '#b6c9d8'
            property string shadow: '#000000'
            property string source_color: '#455c6c'
            property string surface: '#101417'
            property string surface_bright: '#353a3d'
            property string surface_container: '#1c2024'
            property string surface_container_high: '#262a2e'
            property string surface_container_highest: '#313539'
            property string surface_container_low: '#181c20'
            property string surface_container_lowest: '#0a0f12'
            property string surface_dim: '#101417'
            property string surface_tint: '#92cef5'
            property string surface_variant: '#41484d'
            property string tertiary: '#ccc1e9'
            property string tertiary_container: '#4a4263'
            property string tertiary_fixed: '#e8ddff'
            property string tertiary_fixed_dim: '#ccc1e9'
        }
    }

    Palette {
        id: fishy

        text: "#c5bf99"
        text_color: "#afc9d0"
        background: "#13181a"
        background_bright: "#192022"
        border: "#afc9d0"
        accent: "#7aa5b1"
        dull: "#575f62"
        red: "#dd6470"
    }

    component Palette: QtObject {
        required property string text
        required property string text_color
        required property string background
        required property string background_bright
        required property string border
        required property string accent
        required property string dull
        required property string red
    }
}
